### ISSUE TITLE
OPRC v1.3.7

### ISSUE THREAD

**Issue by CcMarc** [numinix/one_page_responsive_checkout_public#1]
Getting the following error:
14-Jul-2015 20:35:39 America/New_York] PHP Warning:  date() expects at least 1 parameter, 0 given in /var/www/zencart/admin/includes/classes/numinix_plugins.php on line 142

This is line 142 from that file:
        if (strtotime(date()+"+1 week") > strtotime($this->loc_expires) && strtotime($this->loc_expires) > date()) {

**Comment by jefflew** [comment]
All repos are being moved to bitbucket.org
