### ISSUE TITLE
Shop with confidence displaying even though configuration html for it is empty.

### ISSUE THREAD

**Issue by tylerdanke** [numinix/one_page_responsive_checkout_public#2]
I see that the confidence box was showing on my site even though Zencart admin > Configuration > One Page Responsive Checkout> Layout > Shop With Confidence HTML> was empty.

I changed Display Confidence Box to false and now it went away. However I thought you should know about the bug in your premium plugin. THIS IS NOT AN ISSUE I AM INTERESTED IN PAYING TO BE FIXED. This is resolved for me at this time.  I just figured that you would like to know about the issue.

![2015-11-03-confidence-box](https://cloud.githubusercontent.com/assets/7409084/10917636/6ab2ae62-8227-11e5-8216-c4feee3c0fc5.PNG)

**Comment by jefflew** [comment]
Your template must be customized because the default badges to show are OpenSSL and PayPal if the HTML field is left empty but the option is enabled. This isn't a bug.
